name: Provenance CI example

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  provenance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check publishing checkpoints
        uses: ./
        with:
          config: examples/pass.yml
